### PR TITLE
Update hot.json

### PR DESCRIPTION
**Pull request by RaydenKonig**
mountains and volcanoes make the region uglier and uncomfortable

### CODE REVIEW

**Comment by CocoTheOwner** [comment]
Mountains, agree, volcanoes, I like them being in the deserts, if they're not too frequent.

**Comment by NextdoorPsycho** [comment]
Hard no from me, this is a HOT-TAKE *joke*
but no, it adds diversity to the desert, make them more rare by adding the dunes/desert more instead of removing them

**Comment by CocoTheOwner** [comment]
Imo removing the mountains of a good idea, they don't realistically go into a dessert, and I think that the volcanoes should be less frequently spawning, but not be removed.
The other biomes that are removed shouldn't be.
Just my take

**Comment by NextdoorPsycho** [comment]
> Imo removing the mountains of a good idea, they don't realistically go into a dessert, and I think that the volcanoes should be less frequently spawning, but not be removed.
> The other biomes that are removed shouldn't be.
> Just my take

agree^

**Comment by NextdoorPsycho** [comment]
review my changes papi

**Pull request merged**
