### PR TITLE
I did something cool

### PR DESCRIPTION
**Pull request by RePixelatedMC**
- New Miountain Biome ( Frozen region )
- New Gen

### CODE REVIEW

**Comment by svdgoor** [comment]
No objects on your mountain?

Also the mountain is never used, perhaps include it in a region?

**Comment by RePixelatedMC** [comment]
I messed a bit up

**Comment by RePixelatedMC** [comment]
Like for debugging purposes i removed the biome from the region but I forgot to add it back apparently lol

**Comment by RePixelatedMC** [comment]
And the mountains dont need to contain objects / i didn’t include them cause i didn’t want

**Pull request closed without merging**
