### PR TITLE
Update temperate.json

### PR DESCRIPTION
**Pull request by RaydenKonig**
long ago, he had modified this biome so that it is in the tropical region

therefore, I think it looks strange in the temperate region because of its biome color.

What do you think?

### CODE REVIEW

**Comment by NextdoorPsycho** [comment]
i like it, so its a no from me. it to add spice to the region. i want it

**Comment by CocoTheOwner** [comment]
Then change the terrain colour to match that of the region's it is in.

**Comment by RaydenKonig** [comment]
if they do this, it would be good if they create a variant for the tropical region

**Comment by NextdoorPsycho** [comment]
> Then change the terrain colour to match that of the region's it is in.

the point of it is to be like a bruised part of the land. like its the scruff on the skin. this is the place.

**Comment by NextdoorPsycho** [comment]
```json
"children": [
        "temperate-wilds"
    ],
    "childStyle": {
        "style": "IRIS",
        "fracture": {
            "style": "VASCULAR"
        }
    },
```
Add that code to the biome "temperate-plateau"
and ill approve the change here

**Pull request merged**
