### PR TITLE
Overworld 2001 Update

### PR DESCRIPTION
**Pull request by cyberpwnn**
* Major cleanup, biome ids and names are much cleaner and more organized now
* Fixed an issue that caused acacia trees to place in a corrupted way
* Fixed tropical wilds (they were empty)
* Fixed igloos having random holes at the base of the ladder
* Fixed several missing objects
* Overhauled the Temperate plains & forests
* Tweaked colors in a few biomes (see changes below)
* Fixed the Tropical Jungle issue (beilg all bad and semi submerged)
* Simplified the terrain maps to simplex, no visual difference at all
* Object Reduction in temperate
* fixed lines of trees in the temperate... 
* Object modification in the desert's
* Deserts actually show up kek
* fixed a few object errors, and config errors
* removed decorators in lakes??????
* Modified colors / Lush-ness in temperate plateau
* Autumn biome *dab*
* edited stronghold height (lower) to prevent popouts
* Added the Cambian Drift Swamp biome
* Changed Mob Dispersion, again thanks to @StrangeOne101  

https://i.imgur.com/akNWUBr.jpeg <- new biome distro, all working to my liking, (Ignore that its cellular, that was for a test of noise at the same time, nowherecellular is the same result in terms of biome dispersion

*updated*

### CODE REVIEW

**Comment by cyberpwnn** [comment]
Waiting on #156

**Comment by cyberpwnn** [comment]
Also waiting on 1.5.9 for studio changes

**Comment by CocoTheOwner** [comment]
I have a fix ready for the missing objects but cannot push to master.

**Comment by cyberpwnn** [comment]
> I have a fix ready for the missing objects but cannot push to master.

PR

**Comment by CocoTheOwner** [comment]
#158

**Comment by cyberpwnn** [comment]
Last item: Waiting on Iris 1.5.9

**Comment by cyberpwnn** [comment]
1.5.9 Released, Capable of release

**Comment by NextdoorPsycho** [comment]
fixed https://github.com/IrisDimensions/overworld/issues/128

**Comment by NextdoorPsycho** [comment]
Phatt merge

**Review by NextdoorPsycho — COMMENTED** [review]
Merged

**Pull request merged**
