### PR TITLE
Best i can do with the ores

### PR DESCRIPTION
**Pull request by NextdoorPsycho**

### CODE REVIEW

**Review by svdgoor — APPROVED** [review]

**Comment by CocoTheOwner** [comment]
This looks good, still.

**Comment by NextdoorPsycho** [comment]
not merging till dan fixes "bottom" tag in regions

**Comment by CocoTheOwner** [comment]
As discussed in Discord, the issue with the new rock type is all that concerns me here. Approved if that is resolved.

**Comment by NextdoorPsycho** [comment]
I **can** merge now, but im using a jar thats not ready yet lol

**Pull request merged**
