### PR TITLE
Drop the structures rarity

### PR DESCRIPTION
**Pull request by NextdoorPsycho**

### CODE REVIEW

**Comment by NextdoorPsycho** [comment]
Fixed some formatting issues with json
Fixed Village Rates (less)
Removed floating region shit (my bad) hard to find, but it happens
Dropped biome zoom
Made biomes // Regions Smaller (in a 5,000x5.000 you cant see all the biomes, thats a problem for me) you should be able to see at least 90 of them in a random seed in a 5k map.

**Review by StrangeOne101 — APPROVED** [review]

**Comment by NextdoorPsycho** [comment]
Refactored, Did a pregen to test, am still looking into the biome size and im going to see if this is right with a pregen. will update and make commits if needed. but in a 5kx5kmap, all biomes should be at least seen once (or 90%)

**Comment by NextdoorPsycho** [comment]
https://i.imgur.com/lTwads7.jpeg
in a 5k all biomes now spawn properly
yay!

**Comment by StrangeOne101** [comment]
Sizing looks good now 👍

**Review by svdgoor — CHANGES_REQUESTED** [review]
1. Where is redstone ore now? You replaced redstone ore with copper, and now there's 2 copper and 0 redstone.
2. I like that you renamed the biome files, good job
3. Rarities on jigsaws look good.
4. I like how some regions have more of certain resources
5. Not sure if I'm fond of mushroom stems in the mushroom region though
6. Why are you removing deepslate objects? Where is deepslate now controlled from?
7. Unsure why you decided to make the regions and biomes smaller, personally not very fond of that change, perhaps it's a bit too abrupt. I would say the biome zoom is fine, but the region zoom decrease of 40% is perhaps a bit much.
8. Didn't personally check every chest for loot table changes, but they look fine to me.

**Comment by CocoTheOwner** [comment]
Also I'm not completely sure on what you need a plugin update for for this. Could you elaborate on that? Can you split off the part that requires a plugin update and put that into a different PR so we can already merge this?

**Comment by NextdoorPsycho** [comment]
Deepslate is now and supposed to be region based

**Comment by NextdoorPsycho** [comment]
Its to add to the depth of the mushroom biome, looks really cool underground when you see a smol stem while mining. sot the idea from one of the peeps here

**Comment by NextdoorPsycho** [comment]
7:
This is a needed change
i pregenerated like 7 maps with @StrangeOne101 and rendered them
in a 1k, 5k, and 15k map there are only 3 biomes. like thats not ok.
in ANY pregen, if its 10k there should be at least 90% of all biomes, being that we tell people that 20k is optimal, how is it optimal if they never get to see any of the biomes... If in a pregen of 10k i cant see all 12 regions, and at least 150 of the 170biomes then it needs to be changed

**Review by svdgoor — APPROVED** [review]
Looks solid. Nice spotting the mushroom region effects

**Review by ghost — APPROVED** [review]

**Comment by CocoTheOwner** [comment]
Question: What does the overworld version number mean? Why don't we use that to indicate the version of the pack (1.16 / 1.17+ etc)

**Comment by ArMiN231** [comment]
> Question: What does the overworld version number mean? Why don't we use that to indicate the version of the pack (1.16 / 1.17+ etc)

That was my idea to help us with supporting users.

**Comment by StrangeOne101** [comment]
> Question: What does the overworld version number mean? Why don't we use that to indicate the version of the pack (1.16 / 1.17+ etc)

If a user tries to update the pack and the version is different, it'll warn them that it will break existing worlds. Truthfully, any time we touch biome sizes, biome rarities or the amount of biomes, we should increment this

**Comment by CocoTheOwner** [comment]
different PR please
havent tested it.

**Comment by NextdoorPsycho** [comment]
> > Question: What does the overworld version number mean? Why don't we use that to indicate the version of the pack (1.16 / 1.17+ etc)
> 
> If a user tries to update the pack and the version is different, it'll warn them that it will break existing worlds. Truthfully, any time we touch biome sizes, biome rarities or the amount of biomes, we should increment this

Whenever i make a change ill try to remember to update the number, but leave version at 2

**Comment by CocoTheOwner** [comment]
I wasn't assigned for approval, but it looks good either way.

**Pull request merged**
