### PR TITLE
WIP Different noise for separating hot/cold.

### PR DESCRIPTION
**Pull request by svdgoor**
I need some feedback to gauge if this effort is well spent.

The idea behind the change is that this eliminates the chance that, for example, hot and cold regions spawn side-by-side.
image
This is the current state of the generator, showing a gradient from (yellow) hot -> tropical -> swamp -> mushroom -> tundra -> temperate -> frozen (blue). This is not ideal yet, since there should not be a line of mushroom, tundra, temperate or swamp around frost/hot+tropical regions, so I would have to merge those into one region and modify the style for that region so the biomes from those individual regions still end up in groups/clusters.

What do you think?

### CODE REVIEW

**Comment by NextdoorPsycho** [comment]
i mean a line is ok, just make it fracture into static with a multiplier, but if you can get this working / nice ill look it over and give it a test

**Comment by svdgoor** [comment]
Status update:
image

current state of the regions. Blue is low-temperature (frozen), green is mid-temperature (swamp, temperate, tundra, mushrooms) and yellow is high-temperature (hot, tropical). We will probably want to increase the size of the mid-temp a bit.

image
Ocean biomes. Need to increase biome zoom on mid-temp drastically.

image
Land biome sizes may look decent but a lot of them have the same color, so do not be fooled. We need to trial-and-error our way through the sizes of these biomes. I think they should be zoomed in on quite a bit more.

Rendering the actual biome layers fully shows what I mean:
image

Looking for feedback. Perhaps from people from the community too!
Edit: Better vision render.

**Comment by ghost** [comment]
Screenshot 2022-08-31 111205
@CocoTheOwner a screenshot of the 5k pregen

**Comment by NextdoorPsycho** [comment]
Status?

**Comment by svdgoor** [comment]
Unchanged. No time at the moment to thoroughly look this though. Just started the academic year n gotta manage a team ATM. Maybe this or next weekend. Anyone interested and smart enough can continue this if they want

**Comment by ghost** [comment]
@CocoTheOwner and @NextdoorPsycho I'll add those changes to my PR, so we have one PR with everything (merge conflicts). I really like the temperature system and it should be utilised in the next big overworld update

**Comment by svdgoor** [comment]
I still haven't gotten around to checking out how it looks on Opal's server, but you definitely can.
If you likey then you mergey

**Pull request closed without merging**
