### PR TITLE
Rename Small_Valley.json to small_valley.json

### PR DESCRIPTION
**Pull request by RePixelatedMC**

### CODE REVIEW

**Comment by IPECTER** [comment]
Rename small_valley to small-valley

**Comment by RePixelatedMC** [comment]
> Rename small_valley to small-valley

 rsomething went wrong on nexdoors side so it was with capital letters but the "code" requested it without capital letters

**Comment by IPECTER** [comment]
> > Rename small_valley to small-valley
> 
> rsomething went wrong on nexdoors side so it was with capital letters but the "code" requested it without capital letters

https://github.com/IrisDimensions/overworld/blob/9cbd8daa3a54b9c3e0390fa3e6ae138c41d2a293/regions/hot.json#L8

**Comment by RePixelatedMC** [comment]
> > > Rename small_valley to small-valley
> > 
> > 
> > rsomething went wrong on nexdoors side so it was with capital letters but the "code" requested it without capital letters
> 
> https://github.com/IrisDimensions/overworld/blob/9cbd8daa3a54b9c3e0390fa3e6ae138c41d2a293/regions/hot.json#L8

exactly = Rename Small_Valley.json to small_valley.json

**Comment by IPECTER** [comment]
Doesn't Iris distinguish between - and _?

**Comment by RePixelatedMC** [comment]
> Doesn't Iris distinguish between - and _?

wait a sec that overlooked i the issue was capital letters but thats a issue also

**Comment by RePixelatedMC** [comment]
thats also fixed now

**Comment by RePixelatedMC** [comment]
merged with another pr

**Pull request closed without merging**
