### PR TITLE
Stops painting big ass trees

### PR DESCRIPTION
**Pull request by svdgoor**

### CODE REVIEW

**Comment by svdgoor** [comment]
image

**Comment by svdgoor** [comment]
oops deleted the repo on my acc, changes still good tho

**Comment by NextdoorPsycho** [comment]
no

**Comment by svdgoor** [comment]
@NextdoorPsycho why?
Did you look at the image?

**Comment by svdgoor** [comment]
The roots of these trees are meant to be the basis, those do not need to be painted onto the terrain, and it causes very weird artifacts like this, no?

**Pull request closed without merging**
