### PR TITLE
Rename and reorder

### PR DESCRIPTION
**Pull request by CocoTheOwner**
Finished the remaining biomes.

Renamed a small amount of files and reworked small things that were plain stupid (removing self-children etc)

I reordered the dimension file (and removed superfluous settings, which did the same as default) and added some headers.

### CODE REVIEW

**Comment by CocoTheOwner** [comment]
To prevent pain caused by #83 I added the changes discussed there here.

**Comment by NextdoorPsycho** [comment]
This was already merged?

**Comment by CocoTheOwner** [comment]
yes but there is MOAR

**Comment by CocoTheOwner** [comment]
also what you merged with master broke the pack, just saying :]

**Comment by cyberpwnn** [comment]
When a pr is merged, make new ones please. Your changes were manually shoved in

**Comment by CocoTheOwner** [comment]
Will do. Reason I did not was that when the original was merged it was broken. I also said I was not yet done.

**Pull request closed without merging**
