### PR TITLE
Update temperate.json

### PR DESCRIPTION
**Pull request by RaydenKonig**
Increased size in temperate region biomes for improvement
aesthetic and more similar to vanilla gameplay

### CODE REVIEW

**Comment by NextdoorPsycho** [comment]
> Increased size in temperate region biomes for improvement
> aesthetic and more similar to vanilla gameplay

We are not after vanilla gameplay, if we were we would just use vanilla

**Comment by RaydenKonig** [comment]
well then I don't use that word anymore.
 
what I mean is that the biomes used to be very small within this region.

**Comment by NextdoorPsycho** [comment]
> well then I don't use that word anymore.
> 
> what I mean is that the biomes used to be very small within this region.

oh! ok in that case ill look into the map and see give me like 20 min

**Comment by CocoTheOwner** [comment]
Approved by me

**Pull request merged**
